# The following lines were added by compinstall
zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename '/home/jude/.zshrc'

# Autocompletion
autoload -Uz compinit
compinit

# Prompt
eval "$(starship init zsh)"

# Plugins
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source ~/.config/shell/env
