-- #######################################################################################
-- AUTOGENERATED HYPRLAND CONFIG.
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.
-- #######################################################################################

local terminal = "alacritty"
local menu = "rofi -show drun"

local function set_cursor_size(size)
	hl.env("XCURSOR_SIZE", size)
	hl.env("HYPRCURSOR_SIZE", size)
end


-- DEPENDENCIES --
require('recolor')
local gaps = require('gaps')

-- AUTOSTART --
set_cursor_size(24)

hl.on("hyprland.start", function ()
	hl.exec_cmd("waybar")
	hl.exec_cmd("swaybg -i ~/.config/colors-wallpaper/* -m fil")
	hl.exec_cmd("~/.config/hypr/toggle-gaps.sh")
end)


-- MONITOR --
hl.monitor({
	output = "",
	mode = "highrr",
	position = "auto",
	scale = 1
})


-- SETTINGS --
hl.config({
	general = {
		border_size = 1,
		resize_on_border = false,
		allow_tearing = false,
		layout = "master"
	},
	decoration = {
		rounding_power = 2,
		active_opacity = 1.0,
		inactive_opacity = 1.0,
		shadow = { enabled = false },
		blur = { enabled = false }
	},
	animations = {
		enabled = false
	},
	dwindle = {
		preserve_split = true
	},
	master = {
		new_status = "master"
	},
	input = {
		kb_layout = "us",
		repeat_delay = 150,
		repeat_rate = 30,
		follow_mouse = 1,
		sensitivity = 0,
		accel_profile = "flat",
		touchpad = {
			natural_scroll = false
		}
	},
	cursor = {
		hide_on_key_press = true
	},
	misc = {
		disable_autoreload = true,
		force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = false -- If true disables the random hyprland logo / anime girl background. :(
	}
})

gaps.set_size({
	gaps_in = 8,
	gaps_out = 16,
	rounding = 4
})

gaps.set_gaps_on(true)
Recolor()


--require("recolor.conf")


-- KEYBINDS --
local main_mod = "SUPER"

local quit_cmd = "command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'"

hl.bind(main_mod .. " + SHIFT + Return", hl.dsp.exec_cmd(terminal))
hl.bind(main_mod .. " + C",              hl.dsp.window.close())
hl.bind(main_mod .. " + SHIFT + Q",      hl.dsp.exec_cmd(quit_cmd))
hl.bind(main_mod .. " + Space",          hl.dsp.window.float({ action = "toggle" }))
hl.bind(main_mod .. " + P",              hl.dsp.exec_cmd(menu))
hl.bind(main_mod .. " + X",              hl.dsp.layout("togglesplit"))
hl.bind(main_mod .. " + F",              hl.dsp.window.fullscreen())

-- navigation
hl.bind(main_mod .. " + Return",    hl.dsp.layout("swapwithmaster master"))
hl.bind(main_mod .. " + J",         hl.dsp.layout("cyclenext"))
hl.bind(main_mod .. " + K",         hl.dsp.layout("cycleprev"))
hl.bind(main_mod .. " + SHIFT + J", hl.dsp.layout("swapnext"))
hl.bind(main_mod .. " + SHIFT + K", hl.dsp.layout("swapprev"))
hl.bind(main_mod .. " + H",         hl.dsp.layout("mfact -0.05"))
hl.bind(main_mod .. " + L",         hl.dsp.layout("mfact +0.05"))

-- custom scripts
hl.bind(main_mod .. " + M", hl.dsp.exec_cmd("~/.config/hypr/toggle-layout.sh monocle"))
hl.bind(main_mod .. " + G", gaps.toggle)
hl.bind(main_mod .. " + W", hl.dsp.exec_cmd("~/.config/scripts/wallpaper.sh"))
hl.bind(main_mod .. " + T", hl.dsp.exec_cmd("~/.config/scripts/theme.sh"))
hl.bind(main_mod .. " + B", hl.dsp.exec_cmd("killall -SIGUSR1 waybar"))

-- switch workspace
for i = 1, 10 do
    local key = i % 10 -- 10 maps to key 0
    hl.bind(main_mod .. " + " .. key,             hl.dsp.focus({ workspace = i}))
    hl.bind(main_mod .. " + SHIFT + " .. key,     hl.dsp.window.move({ workspace = i, follow = false }))
end

-- Example special workspace (scratchpad)
hl.bind(main_mod .. " + S",         hl.dsp.workspace.toggle_special("magic"))
hl.bind(main_mod .. " + SHIFT + S", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with main_mod + scroll
hl.bind(main_mod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(main_mod .. " + mouse_up",   hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with main_mod + LMB/RMB and dragging
hl.bind(main_mod .. " + mouse:272", hl.dsp.window.drag(),   { mouse = true })
hl.bind(main_mod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Laptop multimedia keys for volume and LCD brightness
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"), { locked = true, repeating = true })
hl.bind("XF86AudioLowerVolume", hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),      { locked = true, repeating = true })
hl.bind("XF86AudioMute",        hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),     { locked = true, repeating = true })
hl.bind("XF86AudioMicMute",     hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),   { locked = true, repeating = true })
hl.bind("XF86MonBrightnessUp",  hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"),                  { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown",hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"),                  { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext",  hl.dsp.exec_cmd("playerctl next"),       { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay",  hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev",  hl.dsp.exec_cmd("playerctl previous"),   { locked = true })

-- Prtscreen
hl.bind("Print", hl.dsp.exec_cmd("grim"))
hl.bind(main_mod .. " + Print", hl.dsp.exec_cmd("grim -g \"$(slurp)\""))

hl.window_rule({
    -- Fix some dragging issues with XWayland
    name  = "fix-xwayland-drags",
    match = {
        class      = "^$",
        title      = "^$",
        xwayland   = true,
        float      = true,
        fullscreen = false,
        pin        = false,
    },

    no_focus = true,
})

hl.window_rule({
    name  = "move-hyprland-run",
    match = { class = "hyprland-run" },

    move  = "20 monitor_h-120",
    float = true,
})
