source = ~/.config/hypr/colors-hypr.conf
general {
    # https://wiki.hypr.land/Configuring/Variables/#variable-types for info about colors
    col.active_border = $color_fg
    col.inactive_border = $color_subtle
}
