
# The following lines were added by compinstall

zstyle ':completion:*' completer _complete _ignored
zstyle :compinstall filename '/home/jude/.zshrc'

# Autocompletion
autoload -Uz compinit
compinit

# End of lines added by compinstall
# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
unsetopt autocd beep
bindkey -v
# End of lines configured by zsh-newuser-install

# Adding bin to path
path+=('/home/jude/bin');
path+=('/home/jude/.cargo/bin');
export PATH

# Aliases
alias fd="cd ~; cd \$(find * -type d | fzf)"
alias ls="ls --color=auto"
alias t0="tmux attach -t 0"
alias grep="grep --color=auto"

# Powerline
powerline-daemon -q
. /usr/share/powerline/bindings/zsh/powerline.zsh

eval $(thefuck --alias)
